Maintenance on GHA to keep reporting going (#3)
* test node apps against v16 and v18 in Actions

* Add names of implementation to logs in specfiles

* Only create index server instance (a lightly modified restify server) if needed

* Bump package versions

* Update include for @fastify/basic-auth

* Remove serializers from index impl

* Bump versions in benchmark

* Try restify without any async

* Remove fail-fast for matrix strategy

* error message instead of failing the job

* Run tests off of node 16

* Fix definition of async restify routes

* Update GHA versions

* Test routes.js with async only handlers

* Update NodeJS packages (Express and Koa)

diff --git a/.github/workflows/node-test-containerized.yml b/.github/workflows/node-test-containerized.yml
--- a/.github/workflows/node-test-containerized.yml
+++ b/.github/workflows/node-test-containerized.yml
@@ -11,9 +11,12 @@ jobs:
   install-test:
     name: Node application tests
     strategy:
+      fail-fast: false
       matrix:
-        node: ['14', '16']
-    runs-on: 'ubuntu-20.04'
+        node: ['18', '20']
+        runson: ['ubuntu-20.04', 'ubuntu-22.04']
+        postgresversion: ['14.2-alpine']
+    runs-on: ${{ matrix.runson }}
     # These run alongside the job.
     # See:
     # - https://docs.github.com/en/actions/using-containerized-services/about-service-containers
@@ -21,7 +24,7 @@ jobs:
     services:
       # label for service - since this job doesn't run in a container, this service is accessible at localhost
       database:
-        image: postgres:14.2-alpine
+        image: postgres:${{ matrix.postgresversion }}
         ports:
           - 5432:5432
         env:
@@ -50,7 +53,7 @@ jobs:
       # https://github.com/actions/setup-node
       # https://github.com/actions/cache is no longer needed with setup-node v2
     - name: Setup Node with npm cache
-      uses: actions/setup-node@v3
+      uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node }}
         cache: 'npm'
@@ -59,11 +62,10 @@ jobs:
       run: npm install
 
     - name: Run tests with mocks
-      run: npm run test
+      run: npm run test || echo '::error file=package.json,title=npm::default target failed, ${{matrix.node}}'
 
     - name: Run tests against live Postgres server
-      if: matrix.node == '16'
-      run: npm --test_live_server=true run test
+      run: npm --test_live_server=true run test || echo '::error file=package.json,title=npm::test_live_server failed, ${{matrix.node}}'
       env:
         PGUSER: acronymapi
         PGPASSWORD: password
