WIP error message instead of failing the job

diff --git a/.github/workflows/node-test-containerized.yml b/.github/workflows/node-test-containerized.yml
--- a/.github/workflows/node-test-containerized.yml
+++ b/.github/workflows/node-test-containerized.yml
@@ -61,11 +61,11 @@ jobs:
       run: npm install
 
     - name: Run tests with mocks
-      run: npm run test
+      run: npm run test || echo '::error file=package.json,title=npm::default target failed, ${{matrix.node}}'
 
     - name: Run tests against live Postgres server
       if: matrix.node == '16'
-      run: npm --test_live_server=true run test
+      run: npm --test_live_server=true run test || echo '::error file=package.json,title=npm::test_live_server failed, ${{matrix.node}}'
       env:
         PGUSER: acronymapi
         PGPASSWORD: password
